// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIrjSgtETu7pmb6dkMC53k295qCZV3pJ4',
    appId: '1:752057448311:web:7c33eea1175be01bff1372',
    messagingSenderId: '752057448311',
    projectId: 'student-assignment-reminder',
    authDomain: 'student-assignment-reminder.firebaseapp.com',
    storageBucket: 'student-assignment-reminder.firebasestorage.app',
    measurementId: 'G-1Y60EW0XRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaXhNSOTHu8Df26Q_ykLCx6KfmCZ6Khjc',
    appId: '1:752057448311:android:1765e5f144d254b8ff1372',
    messagingSenderId: '752057448311',
    projectId: 'student-assignment-reminder',
    storageBucket: 'student-assignment-reminder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_F3YcfHVg6Dl3NFjpMHIBxCBmtIHBgdQ',
    appId: '1:752057448311:ios:4a03ee6eda58ee22ff1372',
    messagingSenderId: '752057448311',
    projectId: 'student-assignment-reminder',
    storageBucket: 'student-assignment-reminder.firebasestorage.app',
    iosBundleId: 'com.example.studentAssignmentReminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_F3YcfHVg6Dl3NFjpMHIBxCBmtIHBgdQ',
    appId: '1:752057448311:ios:4a03ee6eda58ee22ff1372',
    messagingSenderId: '752057448311',
    projectId: 'student-assignment-reminder',
    storageBucket: 'student-assignment-reminder.firebasestorage.app',
    iosBundleId: 'com.example.studentAssignmentReminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIrjSgtETu7pmb6dkMC53k295qCZV3pJ4',
    appId: '1:752057448311:web:90b15d67592e1656ff1372',
    messagingSenderId: '752057448311',
    projectId: 'student-assignment-reminder',
    authDomain: 'student-assignment-reminder.firebaseapp.com',
    storageBucket: 'student-assignment-reminder.firebasestorage.app',
    measurementId: 'G-86BT9K2SVX',
  );
}
